'      *********    DO NOT MODIFY THIS FILE     *********
'      This file is regenerated by a design tool. Making
'      changes to this file can cause errors.
Imports System
Imports System.ComponentModel
Namespace Expression.Blend.SampleData.SampleDataSource
' To significantly reduce the sample data footprint in your production application, you can set
' the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#If DISABLE_SAMPLE_DATA Then
    Friend Class SampleDataSource
    End Class
#Else

    Public Class SampleDataSource
        Implements INotifyPropertyChanged

        Public Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged

        Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
            Dim handler As PropertyChangedEventHandler = Me.PropertyChangedEvent
            If handler IsNot Nothing Then
                RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
            End If
        End Sub

        Public Sub New()
            MyBase.New()
            Try
                Dim resourceUri As Uri = New Uri("/ardbeg;component/SampleData/SampleDataSource/SampleDataSource.xaml", UriKind.RelativeOrAbsolute)
                System.Windows.Application.LoadComponent(Me, resourceUri)
            Catch __exception As System.Exception
            End Try
        End Sub

        Private _Property1 As Double = 0

        Public Property Property1() As Double
            Get
                Return Me._Property1
            End Get

            Set(ByVal value As Double)
                If Not Object.Equals(Me._Property1, value) Then
                    Me._Property1 = value
                    Me.OnPropertyChanged("Property1")
                End If
            End Set
        End Property
    End Class
#End If
End Namespace
